### ISSUE TITLE
Not working on OSX 10.8.4

### ISSUE THREAD

**Issue by ktaragorn** [manastech/homebrew-crystal#7]
I installed using  brew tap/update/install instructions, and now I cannot run the latest 0.7.6 version.

```
$ crystal
dyld: _dyld_bind_fully_image_containing_address() error
dyld: Symbol not found: ___strlcpy_chk
  Referenced from: /usr/local/Cellar/crystal-lang/0.7.6/embedded/bin/crystal
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/Cellar/crystal-lang/0.7.6/embedded/bin/crystal
/usr/local/bin/crystal: line 6:  5200 Trace/BPT trap: 5       "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

**Comment by ktaragorn** [comment]
Xcode and command line tools are installed. 
This error abt `__strlcpy_chk` when googled yields results about issues with osx system git version.. not sure how it is linked..

**Comment by ktaragorn** [comment]
installing via .pkg not working either.. trying source

**Comment by ktaragorn** [comment]
I cant build from source because I need a working crystal compiler..

**Comment by waj** [comment]
Does 0.7.5 version work on your machine?

**Comment by ktaragorn** [comment]
Nope, same error

**Comment by ktaragorn** [comment]
Checked few other versions. Version 0.6.1 worked, but version 0.7.0 didnt.

**Comment by ktaragorn** [comment]
I upgraded to yosemite and it is now fine. Please feel free to close if support for 10.8.x is officially not provided
